kind: pipeline
name: default

steps:
- name: static
  image: node:10.16
  environment:
    VERSION_TAG: $DRONE_TAG
  commands:
  - make static

- name: appdaemon
  image: golang:1.12
  environment:
    VERSION_TAG: $DRONE_TAG
  commands:
  - go get github.com/rakyll/statik
  - make release
  - ls bin

- name: docker
  image: plugins/docker
  settings:
    repo: kimkit/appdaemon
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    files: bin/appdaemon.*.*

trigger:
  event:
    - tag
