dsn: "root@tcp(localhost)/base"
sql: "select id,name,script from luascripts where status = 1 and id > %d order by id asc limit 64"
idname: id
idinit: 0
libs:
  runtags: |
    function runtags(jobname, args)
        -- args = {}
        -- args["t1"] = {"arg1"}
        -- args["t2"] = {"arg2"}
        local res, err = redis.call("#", "job.list", jobname .. "_")
        if err ~= nil then
            return err
        end
        for k, v in ipairs(res) do
            tag = string.sub(v, string.len(jobname) + 4)
            if args[tag] == nil then
                redis.call("#", "job.stop", string.sub(v, 3))
            end
        end
        for k, v in pairs(args) do
            ret, err = redis.call("#", "luascript.runner", scriptname, k, unpack(v))
            if err ~= nil then
                return err
            end
        end
        return nil
    end
