luascript:
  dbconfig:
    dsn: "root@tcp(localhost)/base"
  sql: "select id,name,script from luascript where status = 1 and id > %d order by id asc limit 64"
  idname: id
  idinit: 0
  libs:
    runtags: |
      function runtags(scriptname, args)
          -- args = {}
          -- args["t1"] = {"arg1"}
          -- args["t2"] = {"arg2"}
          for k, v in pairs(args) do
              local ret, err = redis.call("#", "luascript.runner", scriptname, k, unpack(v))
              if err ~= nil then
                  return err
              end
          end
          return nil
      end
