daemon: false
addr: 127.0.0.1:6380
passwords:
  - admin:abc123
logsdir: logs
reportinterval: 10
stoptimeout: 10
savejobs: false
tasks:
  - name: getipinfo
    rule: "*/10 * * * * * *"
    args: [php, scripts/getipinfo.php]
  - name: getipinfoloop
    rule: 2
    args: [php, scripts/getipinfoloop.php]
