tasks:
  - name: getipinfo
    rule: "*/10 * * * * * *"
    args:
      - php
      - scripts/getipinfo.php
  - name: getipinfoloop
    rule: 2
    args:
      - php
      - scripts/getipinfoloop.php
